version: '3'

services:
  app:
    build: .
    depends_on:
      - database
    env_file: 
      - .env
    volumes:
      - ./:/app

  database:
    image: mariadb:10.4.2-bionic
    volumes: 
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

volumes:
  database: