version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/app.dockerfile
    depends_on:
      - database
      
  nginx:
    build:
      context: ./
      dockerfile: ./.docker/dockerfiles/nginx.dockerfile
    depends_on:
      - app

  database:
    image: mariadb:10.4.2-bionic
    volumes: 
      - database:/var/lib/mysql

volumes:
  database: